name: FAN
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas
  - scikit-learn>=0.20
  - matplotlib
  - seaborn
  - jupyter
  # Extra processing packages
  - lightgbm
  - catboost
  - xgboost
  - category_encoders
  - spacy
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
      - recordlinkage
